version: "3.9"

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: bankcards
      POSTGRES_USER: bankcards
      POSTGRES_PASSWORD: bankcards
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: bankcards
      DB_USER: bankcards
      DB_PASSWORD: bankcards
      JWT_SECRET: wfzPgX12oS7mJnLAVGWMGI0YUA19az1CJhyvC75kpSk=
      AES_KEY_BASE64: SaLJ1e0y3eVXEBXxAeEQo6PGqxDCkBWy6veFf1s7SsI=
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data:
