services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: bankcards
      POSTGRES_USER: bankcards
      POSTGRES_PASSWORD: bankcards
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: bankcards
      DB_USER: bankcards
      DB_PASSWORD: bankcards

      JWT_SECRET: "${JWT_SECRET:?JWT_SECRET is required}"
      AES_KEY_BASE64: "${AES_KEY_BASE64:?AES_KEY_BASE64 is required}"

      JWT_EXP_MIN: "${JWT_EXP_MIN:-60}"
      JWT_ISSUER: "${JWT_ISSUER:-bankcards-api}"

    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data:
